name: Build and verify
on:
  pull_request:
    branches: [ v3 ]
  push:
    branches:
      - '*'
    paths-ignore:
      - '**/*.md'
      - '**/renovate.json'
  workflow_dispatch:

# Cancel running workflows of the same group when commit is added and a new workflow is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job
        os: [ ubuntu-22.04, windows-2022, macos-12 ]
        jvm: [ 11, 17, 21 ]

    # https://github.com/actions
    # https://github.com/marketplace?type=actions
    steps:
      - name: Checkout project
        uses: actions/checkout@v4.1.7

      - name: Setup JVM ${{ matrix.jvm }}
        uses: actions/setup-java@v4.2.2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jvm }}

      # https://github.com/marketplace/actions/gradle-build-action
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0
        with:
          # The Gradle wrapper's version (already the default, putting it here to clarity)
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/v3' }}
          gradle-home-cache-cleanup: true
          gradle-home-cache-includes: |
            caches
            notifications
            jdks
          gradle-version: wrapper

      - name: Build
        if: startsWith(matrix.os, 'ubuntu')
        run: xvfb-run ./gradlew build -P kotlin.jvmToolchain=${{ matrix.jvm }}

      - name: Build
        if: ${{ !startsWith(matrix.os, 'ubuntu') }}
        run: ./gradlew build -P kotlin.jvmToolchain=${{ matrix.jvm }}
