name: JMH
on:
  pull_request:
    branches: [ v3 ]
  push:
    branches:
      - '*'
    paths-ignore:
      - '**/*.md'
      - '**/renovate.json'
  workflow_dispatch:

# Cancel running workflows of the same group when commit is added and a new workflow is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  jmh:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04 ]
        jvm: [ 11, 17, 21 ]

    steps:
      - name: Checkout project
        uses: actions/checkout@v4.2.1

      - name: Setup JVM ${{ matrix.jvm }}
        uses: actions/setup-java@v4.4.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jvm }}

      # https://github.com/marketplace/actions/gradle-build-action
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.1.0
        with:
          # The Gradle wrapper's version (already the default, putting it here to clarity)
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/v3' }}
          gradle-home-cache-includes: |
            caches
            notifications
            jdks
          gradle-version: wrapper

      - name: Build
        run: ./gradlew jmh -P kotlin.jvmToolchain=${{ matrix.jvm }}
